### ISSUE TITLE
Modify legend so that it is appropriate for our dataset

### ISSUE THREAD

**Issue by raudabaugh** [codefordayton/grocer#1]

**Comment by dlangh** [comment]
I will be working on parts of this.  Primarily to modify the checkbox filters so they are appropriate for the Dayton Grocer dataset.  Instead of theatre/subway etc will let you choose the type of grocery store and ultimately the rta busstops

**Comment by dlangh** [comment]
Decided we will remove the grocer checkbox and otherwise leave the legend in place

**Comment by dlangh** [comment]
I removed the grocers checkbox in the legend
