### ISSUE TITLE
Display just a few fields on the map icon pop up

### ISSUE THREAD

**Issue by dwcaraway** [codefordayton/grocer#10]
For selected map icon, only display in popup
- name
- address
- phone number

**Comment by dlangh** [comment]
This is complete. I did a few additional things with this:
1. I changed the width from auto to 300, this seems to be much better. I was set to 'auto' which I think was generally too narrow.  devices with widths < 767 are unchanged.
2. I made the phonenumber a tel: link so users on phones can touch to call, computer users with skype or other suitable app can as well.

**Comment by dwcaraway** [comment]
Looks fantastic Don. Closing this as well.
