### ISSUE TITLE
Category buttons are too dark when inactive on tablet/mobile

### ISSUE THREAD

**Issue by dlangh** [codefordayton/grocer#11]
Not sure why this is yet.  The CSS is basically all bootstrap, but I am sure that is not the intended result.  Inactive buttons look fine on the desktop

**Comment by AMGlett** [comment]
Is the background dark color on light color or light color on dark color in your UI? My guess is, that unless they've made all of those logos CSS, their using PNG based sprites to keep things uniform and small data sizes (SVG and Canvas take up a lot of space for intricate artwork). If their somewhat dark to begin with, you or someone else (perhaps me) might need to go in and edit the PNG file that the sprites are stored. Another option would be to change the surrounding colors to make the logos pop more.

**Comment by dlangh** [comment]
the background is black and the font color is a dark gray, result is barely readable and non-recognizable as a button.  I didn't do anything special with these buttons, just used the standard bootstrap classes 'btn' and 'btn-primary' (for selected buttons).  I have spent zero-time investigating this so far, just wanted to get it added here as an issue

**Comment by dlangh** [comment]
In the event anyone else  takes a look at this I did also add a class 'categories' to this, though I did not style that class, I used that so I could identify the buttons in javascript.  I just did a quick search and I don't see that class styled in any of the included css files for this project.

**Comment by dlangh** [comment]
I figured it out.  I was adding/removing btn-primary class as needed to toggle the "active" state of the button, but I wasn't restoring btn-default which produces the light-grey button, all fixed
