### ISSUE TITLE
Convert icons to SVG from PNG

### ISSUE THREAD

**Issue by dwcaraway** [codefordayton/grocer#17]

**Comment by LeahArmstrong** [comment]
What level or browser support is being provided? It will have an impact on the implementation. SVGs can be used for most of it, but if ie8 or lower are being supported, we can port the svgs to a font-icon set and use it that way.

**Comment by dwcaraway** [comment]
I would focus on what's easiest to implement right now. If it's just the latest safari / chrome / ff / ie, that's just fine.

**Comment by dlangh** [comment]
my feeling with IE 8 an lower is that if the Microsoft no longer supports it, why should we. MS btw dropped support for XP on April 14 and IE 8 along with it.

**Comment by LeahArmstrong** [comment]
@dlangh With the markers, I've implemented the new svg default, but I'm curious. The output renders each marker as an img. Is it possible to wrap that img in a span so that it can be more appropriately styled? For example: 

```
<img src="assets/img/grocery.svg" class="leaflet-marker-icon leaflet-zoom-animated leaflet-clickable" title="5th Street Wine &amp; Deli" tabindex="0" style="margin-left: -12px; margin-top: -28px; width: 30px; height: 40px; -webkit-transform: translate3d(96px, -429px, 0px); z-index: -429;">
```

to do something like this:

```
<span class="grocery"><img src="assets/img/grocery.svg" class="leaflet-marker-icon leaflet-zoom-animated leaflet-clickable" title="5th Street Wine &amp; Deli" tabindex="0" style="margin-left: -12px; margin-top: -28px; width: 30px; height: 40px; -webkit-transform: translate3d(96px, -429px, 0px); z-index: -429;"></span>
```

**Comment by LeahArmstrong** [comment]
I managed to figure this out, and have updated the icons to use the vector format. In ticket b7e79ed19edab64910ffe34c4940fa7081b73904, I converted the icon generator into a divIcon generator, and placed the img inside of it, allowing for more flexibility in the future. Now, each marker can have it's own class, allowing individual styling of each marker color, and the icon is wrapped to be a consistent size, no matter what is placed inside. This should make a more consistent experience.

**Comment by dwcaraway** [comment]
i don't understand it but sounds good to me -- nice, dustin!

On Apr 23, 2014, at 5:45 PM, Dustin Armstrong notifications@github.com
wrote:

I managed to figure this out, and have updated the icons to use the vector
format. In ticket
b7e79edhttps://github.com/codefordayton/grocer/commit/b7e79ed19edab64910ffe34c4940fa7081b73904,
I converted the icon generator into a divIcon generator, and placed the img
inside of it, allowing for more flexibility in the future. Now, each marker
can have it's own class, allowing individual styling of each marker color,
and the icon is wrapped to be a consistent size, no matter what is placed
inside. This should make a more consistent experience.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/codefordayton/grocer/issues/17#issuecomment-41218938
.

**Comment by dlangh** [comment]
Ok, I started to modify the code to load the appropriate icon for each grocery type, but it seems that it loses the background and all I'm left with is the "icon" itself and no background color at all.

I have to admit, I don't know a lot about SVG, but I think given that this grocery app is using leaflet and that we don't create/don't interact with these icons via html directly it makes more sense in this case to fall back to standard PNG files.  Again, it's not a case where we have the <img> tag in our html, leaflet is creating it in the background for us.  The way icons are created in leaflet is by defining  and icon in JS as such:

var csaIcon = L.icon({
    iconUrl: "assets/img/csa.svg",
    iconSize: [30, 30],
    iconAnchor: [12, 28],
    popupAnchor: [0, -25]
    });

I think I get the advantage of SVG from a bit of googling and inspecting the file, but I think for this endevour with leaflet it might end up causing a lot more work to make it work.  I am also not in favor of bending/customizing leaflet itself to make SVG work. Simple PNG files of each grocery type would probably make the most sense for this.

Thanks!

Don

**Comment by LeahArmstrong** [comment]
@dlangh A quick way of resolving the issue that you're having is by doing this:

```
 return L.marker(latlng, {
        icon: L.divIcon({
            html: "<img src='assets/img/grocery.svg'>",
            iconSize: [30, 30],
            iconAnchor: [12, 28],
            popupAnchor: [0, -25]
        }),
        title: feature.properties.name,
        riseOnHover: true
});
```

Just changing it from `L.icon` to `L.divIcon` and putting the image in with `html: "<img src="#">"`

Read more about it [in the leaflet documentation](http://leafletjs.com/reference.html#divicon).

This opens up a fair amount of flexibility in the future without depending on someone who has the original editable file to make more changes, as the svg can be directly manipulated. All that this is doing is adding a `<div>` wrapper around the image for more styling. 

It's nothing complex, but classes can be added to that div to create different colored icons without having to edit an image each time, and the images can be resized without losing clarity.

Let me know if this makes sense. If not I'll try and convert them over.

**Comment by dlangh** [comment]
I didn't know about L.divIcon, that worked  You should see the icons on the site now.

Thanks!

Don
