### ISSUE TITLE
Adjust bounding box of map

### ISSUE THREAD

**Issue by dwcaraway** [codefordayton/grocer#20]
view should be just dayton city boundaries

**Comment by dlangh** [comment]
I zoomed in 3 clicks, thoughts if this works?

**Comment by dwcaraway** [comment]
works for me. cool!

On Tue, Apr 15, 2014 at 8:02 PM, dlangh notifications@github.com wrote:

> I zoomed in 3 clicks, thoughts if this works?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/codefordayton/grocer/issues/20#issuecomment-40549150
> .

## 

Dave Caraway
Civic Hacker / Data Geek
dave@fogmine.com
(937) 985-0867

**Comment by dlangh** [comment]
I'm closing this
