### ISSUE TITLE
Disappearing filters/search

### ISSUE THREAD

**Issue by raudabaugh** [codefordayton/grocer#21]
I shrink the window to get the hamburger menu, click on the hamburger, close out of the filter/search menu, then resizing the window removes the hamburger but doesn't restore the filter/search.

I am on OS X - happens on both Safari 7 and Chrome 34.

**Comment by raudabaugh** [comment]
The bug was introduced in commit 308c4c6c5799d02fdb0777ee2c7712f17e7fc5ab, specifically the assets/js/extensions.js file.

**Comment by dwcaraway** [comment]
@dlangh @raudabaugh reopening for now

**Comment by dlangh** [comment]
I renamed my hide/show prototype functions to hideElem/showElem.  This seems to have fixed the problem.

**Comment by dwcaraway** [comment]
cool, commit and close?

**Comment by dlangh** [comment]
sure, I myself wasn't able to replicate what you described, so I left this open so you could confirm it's fixed before closing, if it works for you feel free to close this.
