### ISSUE TITLE
Add category selectors to nav bar

### ISSUE THREAD

**Issue by dwcaraway** [codefordayton/grocer#7]
Add ability to choose which of the store types to display on the map
- grocery
- convenient
- csa
- farmers
- specialty

**Comment by dlangh** [comment]
I added buttons for each of the noted categories to the navbar.  They are fully functional.

Currently the search field doesn't appear to do anything, but when that is functional, I will probably need to make some changes so results don't include stores filtered out by the category buttons.

Additionally, for mobile, if we present the categories as something other than buttons, I will have to revisit this to make some adjustments

**Comment by dwcaraway** [comment]
Looks awesome Don! Closing the ticket.
